### ISSUE TITLE
0.30 breaks other CPAN modules

### ISSUE THREAD

**Issue by eserte** [toddr/Crypt-OpenSSL-RSA#15] opened 2018-06-02 08:17 UTC
I already opened an issue for a new failure of Authen-NZRealMe (https://github.com/catalyst/Authen-NZRealMe/issues/5) and now stumbled over the next failure: RIZEN/AWS-SNS-Verify-0.0102.tar.gz fails, according to statistical analysis also because of Crypt::OpenSSL::RSA 0.30.

**Comment by eserte** [comment] 2018-06-02 11:48
Another one: UNCLEANDY/GPLVote-SignDoc-Client-0.9.tgz

**Comment by eserte** [comment] 2018-06-04 19:27
Also fails with Crypt::OpenSSL::RSA 0.30: ANTHONYU/Mail-DomainKeys-1.0.tar.gz

**Comment by eserte** [comment] 2018-06-04 20:19
Also: KGRENNAN/Net-OAuth-0.28.tar.gz (mentioned in https://rt.cpan.org/Ticket/Display.html?id=125482 )

**Comment by toddr** [comment] 2018-06-04 20:42
I highly suspect the root cause is https://github.com/toddr/Crypt-OpenSSL-RSA/commit/1149369250b667ff22df50c72a3fce4476636315

**Comment by jwittkoski** [comment] 2018-07-19 21:47
@toddr Did you mean 13df4d34e7cbc9d067f863ddb94260a26df3c9e6 ?

**Comment by toddr** [comment] 2018-07-19 21:48
Yes. Guess I need to get back to this. Sorry it fell through the cracks.

**Comment by jwittkoski** [comment] 2018-07-20 15:35
I think this is a duplicate of #14.

I suspect many other modules that use Crypt::OpenSSL::RSA didn't set the hash algorithm explicitly and so relied on the default setting (sha1). When the Crypt::OpenSSL::RSA default was changed to sha256 many tests which expected test results based on using sha1 broke.

**Comment by toddr** [comment] 2018-07-20 20:59
I'm going to switch the default back to its original and provide an easier way to specify it. The new method should be encouraged not enforced.

**Comment by toddr** [comment] 2018-09-24 19:17
This has been fixed in 247d91bf3278173b0cf4a96255a14bbbc7304074 and released to CPAN as 0.31

**Closed by toddr** 2018-09-24 19:17 UTC
